

services:
  api-backend:
    build: ./backend        
    container_name: meu-backend
    ports:
      - "3000:3000"         
    volumes:
      - ./backend:/app      
      - /app/node_modules   
    environment:
      - PORT=3000           

  app-frontend:
    build: ./frontend       
    container_name: meu-frontend
    ports:
      - "3001:3001"         
    volumes:
      - ./frontend:/app     
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true 
    depends_on:
      - api-backend         