# .github/workflows/deploy.yml

name: Build and Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - gh-pages # 1. O workflow continua a ser acionado por pushes nesta branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 2. Faz o checkout do seu código-fonte da branch 'gh-pages'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # Necessário se você usar temas como submódulos

      # 3. Instala a versão mais recente do Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      # 4. Instala Python e as dependências para seus scripts
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      # 5. Executa seus scripts para buscar dados
      - name: Fetch Data
        run: |
          python ./scripts/fetch_issues.py
          python ./scripts/fetch_milestones.py
          python ./scripts/fetch_atas.py

      # 6. Constrói o site Hugo. O resultado vai para a pasta 'public'
      - name: Build Hugo Site
        run: hugo --minify

      # 7. Publica o conteúdo da pasta 'public' para uma branch de deploy
      # Esta é a etapa mais importante.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # A branch para a qual o site construído será enviado.
          # Pode ser qualquer nome, mas 'gh-pages-deploy' é claro.
          publish_branch: gh-pages-deploy
          # O diretório que contém o site construído.
          publish_dir: ./public