name: Deploy Hugo Site to GitHub Pages

on:
  # Roda quando um push é feito para a branch `source`
  push:
    branches:
      - source # <-- GATILHO CORRETO

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Clona o seu repositório (o código-fonte da branch `source`)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # 2. Instala o Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      # 3. Instala o Python e dependências
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      # 4. Executa seus scripts de busca de dados
      - name: Fetch Issues and Milestones
        run: |
          python ./scripts/fetch_issues.py
          python ./scripts/fetch_milestones.py
      
      - name: Copy Atas
        run: bash ./scripts/copy_atas.sh

      # 5. Constrói o site Hugo
      - name: Build Hugo Site
        run: hugo --minify

      # 6. Faz o deploy para a branch `gh-pages`
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # O branch para onde o site será publicado
          publish_branch: gh-pages # <-- DESTINO CORRETO