name: Build and Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main      

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          submodules: true 
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install requests

      - name: Fetch Data Scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd Git-pages
          python ./scripts/fetch_issues.py
          python ./scripts/fetch_milestones.py
          python ./scripts/fetch_atas.py
          python ./scripts/fetch_doc.py

      - name: Build Hugo Site
        run: hugo --minify --source Git-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-deploy
          publish_dir: ./Git-pages/public 
          commit_message: "Auto-deploy triggered by commit on ${{ github.ref_name }}"